baseURL = "http://example.org/"
languageCode = "en-us"
paginate = 6
theme = "roxo"
title = "roxo"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "O mnie"
url = "#about"
weight = 2
[[menu.main]]
name = "Usługi"
url = "#service"
weight = 3
[[menu.main]]
name = "Doświadczenie"
url = "#resume"
weight = 4
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 5
[[menu.main]]
name = "Kontakt"
url = "#contact"
weight = 6

# Sitemap Menu
[[menu.sitemap]]
name = "O mnie"
url = "o-mnie"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Ostatni artykuł"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Słowackiego 17/5"
email = "julia@bilarzewska.pl"
openingHours = "Godziny konsultacji 8-19"
phone = "+48 690 173 710"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/julia.bilarzewska"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/julia-bilarzewska/"
weight = 2
